### ISSUE TITLE
Doesn't compile with destination Apple Vision Pro

### ISSUE THREAD

**Issue by GerdC** [florianreinhart/Geodesy#4]
The package doesn't compile with destination Apple Vision Pro
(Apple Vision Pro(Designed for iPad) is no problem.

 Coordinate.swift:

    #if os(OSX) || os(iOS)
        import Darwin
    #elseif os(Linux)
        import Glibc
    #endif

Maybe this is enough:

    #if os(OSX) || os(iOS) || os(visionOS)
        import Darwin
    #elseif os(Linux)
        import Glibc
    #endif

**Comment by florianreinhart** [comment]
Thanks, @GerdC!

Could you create a PR for this?

**Comment by GerdC** [comment]
Never did that, but I'll try

**Comment by GerdC** [comment]
Added a fix in PR #5

**Comment by florianreinhart** [comment]
Perfect! Published as [0.2.1](https://github.com/florianreinhart/Geodesy/releases/tag/0.2.1).
